# -*- coding: utf-8 -*-
"""MuestraAnimal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1icE3WM1n2-JWA_Y6-wrY_z0lZBvxqtIX
"""

#!/usr/bin/python3

def _main() -> None:
  # TODO: fixme.
  print("\Please select an animal : \n 1.Dog \n 2.Cat \n 3.Elephant \n 4. Exit");
  option = int(input("\Enter an option :" ));
  while(option!=4):
    pritnAnimal(AnimalMenu(option));
    print("\Please select an animal : \n 1.Dog \n 2.Cat \n 3.Elephant \n 4. Exit");
    option = int(input("\Enter an option :" ));
  print("GOOD BYE");
  pass

def pritnAnimal(animal):
  print(animal);

def AnimalMenu(x):
  if(x==1):
    return """
,-.___,-.
\_/_ _\_/
  )O_O(
 { (_) }
  `-^-'  """;
  if(x==2):
    return """ 
 /\_/\
( o.o )
 > ^ <""";
  if(x==3):
    return """
         __
 .--()°'.'
'|, . ,'
 !_-(_\ """;




if __name__ == '__main__':
  _main()