# -*- coding: utf-8 -*-
"""Sumar2Enteros.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OGSc3QAMZdm3mktwZw-Bl27S5g4ratLR
"""

#!/usr/bin/python3

def _main() -> None:
  # TODO: fixme.
  valx = int(input("\Introduce X : "));
  valy = int(input("\Introduce Y : "));
  sumar(valx,valy)
  pass

def sumar(x, y):
  print(x+y);

if __name__ == '__main__':
  _main()