# -*- coding: utf-8 -*-
"""Sumar numeros de una lista con python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jFYUuj8NzMT87oeqCuOUYf1lMA4K_GXC
"""

#!/usr/bin/python3

def _main() -> None:
  # TODO: fixme.
  lista = list(map(int,input("\nEnter the numbers : ").strip().split()));
  if len(lista)<=1000:
    sumar(lista);
  pass

def sumar(lista):
  print(sum(lista));

if __name__ == '__main__':
  _main()